### PR TITLE
Django < 1.9 in setup.py

### PR DESCRIPTION
**Pull request by vad**

### CODE REVIEW

**Comment by vad** [comment]
Hi, i've sent this PR to fix a problem with TEMPLATE_CONTEXT_PROCESSORS, that now is an OPTION of the django template entry in TEMPLATES but it fails on Django 1.8... tests are run with the old setting.

should I customize cms.test_utils.cli.configure() ?

**Comment by yakky** [comment]
Thanks for this. Yes, the dictionary must be updated. There is already some other conditional configuration you can look at (like https://github.com/yakky/django-cms/blob/develop/cms/test_utils/cli.py#L299)

**Comment by vad** [comment]
@yakky what about 

```
======================================================================
ERROR: test_add_placeholder (cms.tests.page.PagesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/yakky/django-cms/cms/tests/page.py", line 666, in test_add_placeholder
    path = os.path.join(settings.TEMPLATE_DIRS[0], 'add_placeholder.html')
IndexError: tuple index out of range
```
? settings.TEMPLATE_DIRS is deprecated, should we add somewhere a variable that has the value of TEMPLATE_DIRS in django < 1.8 and TEMPLATES[..]['DIRS'] in django 1.8?

**Comment by yakky** [comment]
@vad :+1: 
Anyway I need to check why these error popped up after the succesful runs of a couple of weeks ago

**Comment by yakky** [comment]
I'm merging this and will fix this later

**Comment by vad** [comment]
Thanks! Sorry, but I had no time recently to look more into it

**Comment by yakky** [comment]
@vad Sekizai & co are not up to date with the removal of ``TEMPLATE_DIRS`` etc.
How about merging the current status first and then work on the further improvements for better Django 1.8 support?

**Comment by vad** [comment]
@yakky that's ok, it's important to specify that in the documentation. (Obviously) I do:

```py
TEMPLATE_CONTEXT_PROCESSORS = [
    'django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages',
    'django.template.context_processors.i18n',
    'django.core.context_processors.request',
    'django.template.context_processors.media',
    'django.template.context_processors.static',
    'sekizai.context_processors.sekizai',
    'cms.context_processors.cms_settings',
]

TEMPLATES = [
    {
        'NAME': 'django',
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': TEMPLATE_CONTEXT_PROCESSORS,
        },
    }
]
```

**Comment by yakky** [comment]
@vad Fixed! No need for special cases

**Pull request merged**
