### PR TITLE
Super CMS_PLACEHOLDER_CONF

### PR DESCRIPTION
**Pull request by fmarco**
First attempt to handle excluded plugins and a new CMS_PLACEHOLDER_CONF structured based on regular expressions.

### CODE REVIEW

**Comment by yakky** [comment]
@fmarco could you check test failures?

**Comment by fmarco** [comment]
@yakky Sure, i'll check

**Comment by yakky** [comment]
@fmarco please rebase on top of current develop and check https://github.com/yakky/django-cms/pull/16/files#diff-30bbbc69b08307afff31b82d3a40bfcdR183 because it's not used apparently

**Comment by fmarco** [comment]
@yakky fixed tests and some behaviour

**Comment by yakky** [comment]
Merged upstream, closing this

**Pull request closed without merging**
